name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7924822464119643
  lightness: 0.6533229856286198
  saturation: 0.5832599299028516
  rhythmicContrast: 0.21245177090168
purpose: []
