name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#a1b7b4'
    - '#ff8772'
    - '#781003'
  brandStrength: 1
  lightness: 0.6533229856286198
  saturation: 0.5832599299028516
  rhythmicContrast: 0.25
purpose: []
