name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.16356
typography_spectrum: 0.88757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#a1b7b4'
    - '#ff8772'
    - '#781003'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
