name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.63203
typography_spectrum: 0.87564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64656a'
    - '#3f3e43'
    - '#a7a8ac'
    - '#f9f9f9'
    - '#fedef1'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
