name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.61671
typography_spectrum: 0.88757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1c'
    - '#64656a'
    - '#a7a8ac'
    - '#f9f9f9'
    - '#ecb8be'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
