name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.61499
typography_spectrum: 0.87564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#919191'
    - '#c7c7c7'
    - '#4c4c4c'
    - '#f5f4f2'
    - '#cc656a'
  brandStrength: 1
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
