name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.63715
typography_spectrum: 0.73254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#64656a'
    - '#f6acb9'
    - '#a7a8ab'
    - '#e1e2e3'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
