name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.58603
typography_spectrum: 0.7385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#64656a'
    - '#f6acb9'
    - '#a7a8ab'
    - '#e1e2e3'
  brandStrength: 0
  lightness: 0.6533229856286198
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
