name: Vanessa Crosbie Ramsay
favicon: null
layout_spectrum: 0.6576
typography_spectrum: 0.88757
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#737373'
    - '#be8a92'
    - '#888380'
    - '#2f2e33'
    - '#ffffff'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
